# Generated by Django 3.2.8 on 2021-11-19 03:16

import apps.django_encrypted_filefield.fields
import apps.user.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=150, unique=True, validators=[apps.user.models.CustomUnicodeUsernameValidator()], verbose_name='username')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_project_manager', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.user.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.django_encrypted_filefield.fields.EncryptedImageField(blank=True, null=True, upload_to='img/profile/')),
                ('firstname', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='First Name')),
                ('lastname', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Last Name')),
                ('birth_date', encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True)),
                ('gender', encrypted_model_fields.fields.EncryptedCharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('UNKNOWN', 'Unknown')], null=True, verbose_name='Gender')),
                ('address_line1', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Address line 1')),
                ('address_line2', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Address line 2')),
                ('city', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='City')),
                ('state', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='State')),
                ('code', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Postal Code')),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Example: (123)456-7890', verbose_name='Phone Number')),
                ('time_zone', timezone_field.fields.TimeZoneField(default='America/New_York')),
                ('n_new_msg', models.PositiveIntegerField(default=0)),
                ('n_new_tsh', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_pass', models.CharField(max_length=128)),
                ('pass_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date.today)),
                ('host_confirmed', models.BooleanField(default=False)),
                ('guest_confirmed', models.BooleanField(default=False)),
                ('updated', models.DateField(blank=True, null=True)),
                ('user_grant_perm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to=settings.AUTH_USER_MODEL)),
                ('user_req_perm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('user_grant_perm', 'user_req_perm')},
            },
        ),
    ]
