# Generated by Django 3.2.8 on 2022-05-17 19:59

from django.db import migrations
import encrypted_model_fields.fields
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='America/New_York', verbose_name='Time Zone'),
        ),
    ]
