"""
Django settings for chealth project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

##########################################################
#                 Time Zone Accuracy
##########################################################
# There are 4 levels of timezone in the application.
# 1) Date/Time w/o timezone info, i.e. Fitbit date
# 2) Date/Time attributed to system timezone
# 3) Date/Time attributed to user timezone
# 4) Date/Time attributed to data timezone
# The best display is to display data in data Date/Time (4)
# in a chart with timezone info (if there is a timezone
# change due to summer/winter time, or other).
# Currently, this app is only at accuracy (2).
# TODO: Implement and push to (3) and (4) timezone accuracy.
##########################################################


import os
import dj_database_url
import logging.config
from decouple import config, Csv
from datetime import timedelta
from django.utils.log import DEFAULT_LOGGING
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Intellij Idea does not support pathlib yet
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# Gemini API Key
GEMINI_API_KEY = config('GEMINI_API_KEY')
# settings.py

# Directly define the Gemini API URL
GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'axes',
    'ckeditor',
    'ckeditor_uploader',
    'encrypted_model_fields',
    'zxcvbn_password',
    'timezone_field',
    'rest_framework',
    'rest_framework.authtoken',
    'widget_tweaks',
    'django_celery_results',
    'django_extensions',
    'apps.django_encrypted_filefield',
    'apps.user',
    'apps.msgs',
    'apps.utils',
    'apps.session_security',
    'social_django',
    'apps.dashboard', #for dashboard
] + config('INSTALLED_APPS_EXTRA', cast=Csv(), default='')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.session_security.middleware.SessionSecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'chealth.middleware.GlobalLoginRequiredMiddleware',
    'chealth.middleware.MySocialAuthExceptionMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'axes.middleware.AxesMiddleware'
]

ROOT_URLCONF = 'chealth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/chealth'),
                 os.path.join(BASE_DIR, 'studies/green_diabetes_waste/templates'),
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chealth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'zxcvbn_password.ZXCVBNValidator',
        'OPTIONS': {
            'min_score': 3,
            'user_attributes': ('username', 'email')
        }
    },
    {
        'NAME': 'apps.user.validators.DontRepeatValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'apps.user.backends.EmailOrUsernameModelBackend',
    'social_core.backends.google.GoogleOAuth2',
]


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'axes_cache': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

LANGUAGES = [
    ('en-us', _('English')),
    ('es', _('Spanish'))
]

USE_L10N = True

USE_TZ = True

DATE_FORMAT = 'M d, Y'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = config('STATIC_ROOT', default='/static')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'studies/dhhs/locale'),
    os.path.join(BASE_DIR, 'studies/klife/locale')
]

# CKEditor
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'width': '100%',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            '/',  # put this to force next toolbar on new line
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
        'extraAllowedContent': {
            'p h1': {
                'styles': 'text-align'
            },
            'a': {
                'attributes': '!href'
            },
            'p': {
                'classes': 'text-center'
            },
            'iframe': {
                'attributes': 'allowfullscreen'
            },
            'div': {
                'attributes': 'ytsrc'
            }
         }
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'user.CustomUser'
LOGIN_URL = 'auth'
#for dashboard
# LOGIN_REDIRECT_URL = 'ch:home'
# LOGOUT_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
ADMIN_USERNAME = config('ADMIN_USERNAME', default='overl0ader')

# email service
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX', default='')

PUBLIC_PATHS = [
    '^%s.*' % MEDIA_URL,
    r'^/oauth/.*',
]

CURRENT_SITE_URL = config('CURRENT_SITE_URL', default='')

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# Connection expires duration if not confirmed
CONN_EXPIRES_DAYS = 30

# Django CSP
CSP_DEFAULT_SRC = ("'none'",)
CSP_STYLE_SRC = ("'self'", "fonts.googleapis.com", "'unsafe-inline'")
CSP_SCRIPT_SRC = ("'self'", "'sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo='",
                  "'sha256-ZvOgfh+ptkpoa2Y4HkRY28ir89u/+VRyDE7sB7hEEcI='",
                  "'sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM'")
CSP_IMG_SRC = ("'self'", 'data:')
CSP_FONT_SRC = ("'self'", "fonts.gstatic.com")
CSP_CONNECT_SRC = ("'self'", )
CSP_OBJECT_SRC = ("'none'", )
CSP_BASE_URI = ("'none'", )
CSP_FRAME_ANCESTORS = ("'none'", )
CSP_FORM_ACTION = ("'self'", )
CSP_INCLUDE_NONCE_IN = ('script-src', )

# django_encrypted_filefield
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY', default='')
DEFF_SALT = config('DEFF_SALT', default='')
DEFF_PASSWORD = config('DEFF_PASSWORD', default='')
DEFF_FETCH_URL_NAME = config('DEFF_FETCH_URL_NAME', default='')

# Celery
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='')
CELERY_ACCEPT_CONTENT = config('CELERY_ACCEPT_CONTENT', cast=Csv())
CELERY_TASK_SERIALIZER = config('CELERY_TASK_SERIALIZER', default='')
CELERY_RESULT_SERIALIZER = config('CELERY_RESULT_SERIALIZER', default='')
CELERY_TIMEZONE = config('CELERY_TIMEZONE', default='')
CELERY_ENABLE_UTC = False

# Production Security
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', cast=bool)
SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', cast=bool)
SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', cast=bool)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', cast=bool)
SECURE_PROXY_SSL_HEADER = config('SECURE_PROXY_SSL_HEADER', cast=Csv(post_process=tuple))
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', cast=bool)
X_FRAME_OPTIONS = config('X_FRAME_OPTIONS', default='DENY')

# Session timeout middleware
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', cast=int, default=7776000)
SESSION_SECURITY_WARN_AFTER = config('SESSION_SECURITY_WARN_AFTER', cast=int)
SESSION_SECURITY_EXPIRE_AFTER = config('SESSION_SECURITY_EXPIRE_AFTER', cast=int)
SESSION_EXPIRE_AT_BROWSER_CLOSE = config('SESSION_EXPIRE_AT_BROWSER_CLOSE', cast=bool)
SESSION_SECURITY_INSECURE = config('SESSION_SECURITY_INSECURE', cast=bool)

# Django Axes
AXES_CACHE = 'axes_cache'
AXES_FAILURE_LIMIT = 9
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_RESET_ON_SUCCESS = True
# Keep this consistent with NGINX
AXES_PROXY_COUNT = config('AXES_PROXY_COUNT', cast=int)
AXES_LOCKOUT_URL = '/user/lockout/'
# Nginx with real ip recursive on has already taken care of trusted IPs, number of proxies
# Set AXES_META_PRECEDENCE_ORDER to the real_ip address and keep AXES_PROXY_COUNT = 0
AXES_META_PRECEDENCE_ORDER = ('HTTP_X_REAL_IP', )

UID_PREFIX = config('UID_PREFIX', default='')

# APIs
REDCAP_LIVINGLAB_TOKEN = config('REDCAP_LIVINGLAB_TOKEN', default='')

FITBIT_CLIENT_ID = config('FITBIT_CLIENT_ID', default='')
FITBIT_CLIENT_SECRET = config('FITBIT_CLIENT_SECRET', default='')
FITBIT_REDIRECT_URI = config('FITBIT_REDIRECT_URI', default='')
FITBIT_SUBSCRIPTION = config('FITBIT_SUBSCRIPTION', default=False, cast=bool)
FITBIT_VERIFICATION_CODE = config('FITBIT_VERIFICATION_CODE', default='')

WITHINGS_CLIENT_ID = config('WITHINGS_CLIENT_ID', default='')
WITHINGS_CONSUMER_SECRET = config('WITHINGS_CONSUMER_SECRET', default='')
WITHINGS_CALLBACK_URI = config('WITHINGS_CALLBACK_URI', default='')
WITHINGS_NOTIFY_URI = config('WITHINGS_NOTIFY_URI', default='')

VALIDIC_ORGID = config('VALIDIC_ORGID', default='')
VALIDIC_TOKEN = config('VALIDIC_TOKEN', default='')

TELCARE_CLIENT_ID = config('TELCARE_CLIENT_ID', default='')
TELCARE_CLIENT_SECRET = config('TELCARE_CLIENT_SECRET', default='')
TELCARE_REDIRECT_URI = config('TELCARE_REDIRECT_URI', default='')
TELCARE_NOTIFY_URI = config('TELCARE_NOTIFY_URI', default='')

OMRON_CLIENT_ID = config('OMRON_CLIENT_ID', default='')
OMRON_CLIENT_SECRET = config('OMRON_CLIENT_SECRET', default='')
OMRON_REDIRECT_URI = config('OMRON_REDIRECT_URI', default='')
OMRON_IS_STAGING = config('OMRON_IS_STAGING', default=True, cast=bool)

GARMIN_CONSUMER_KEY = config('GARMIN_CONSUMER_KEY', default='')
GARMIN_CONSUMER_SECRET = config('GARMIN_CONSUMER_SECRET', default='')
GARMIN_CALLBACK_URL = config('GARMIN_CALLBACK_URL', default='')

DEXCOM_CLIENT_ID = config('DEXCOM_CLIENT_ID', default='')
DEXCOM_CLIENT_SECRET = config('DEXCOM_CLIENT_SECRET', default='')
DEXCOM_REDIRECT_URI = config('DEXCOM_REDIRECT_URI', default='')
DEXCOM_SANDBOX = config('DEXCOM_SANDBOX', default=False, cast=bool)

POLAR_CLIENT_ID = config('POLAR_CLIENT_ID', default='')
POLAR_CLIENT_SECRET = config('POLAR_CLIENT_SECRET', default='')
POLAR_REDIRECT_URI = config('POLAR_REDIRECT_URI', default='')

SMARTTHINGS_GAS_ID = config('SMARTTHINGS_GAS_ID', default='')
SMARTTHINGS_CLIENT_ID = config('SMARTTHINGS_CLIENT_ID', default='')
SMARTTHINGS_CLIENT_SECRET = config('SMARTTHINGS_CLIENT_SECRET', default='')
SMARTTHINGS_REDIRECT_URI = config('SMARTTHINGS_REDIRECT_URI', default='')

MMH_CLIENT_ID = config('MMH_CLIENT_ID', default='')
MMH_CLIENT_SECRET = config('MMH_CLIENT_SECRET', default='')
MMH_REDIRECT_URI = config('MMH_REDIRECT_URI', default='')

TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_CALLBACK_URL = config('TWILIO_CALLBACK_URL', default='')

# Rest API
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=999),
    'ROTATE_REFRESH_TOKENS': True,
}

# Logging
# Disable Django's logging setup
LOGGING_CONFIG = None
LOGLEVEL = config('LOGLEVEL', default='INFO')
PLOGLEVEL = config('PLOGLEVEL', default='WARNING')
LOGFILE = config('LOGFILE', default='/tmp/debug.log')
PYTHON_LOGLEVEL = PLOGLEVEL if DEBUG else 'WARNING'
logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            # exact format is not important, this is the minimum information
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        },
        'django.server': DEFAULT_LOGGING['formatters']['django.server'],
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue'
        }
    },
    'handlers': {
        # console logs to stderr
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
        'file': {
            'level': LOGLEVEL,
            'filters': ['require_debug_false'],
            'class': 'logging.FileHandler',
            'formatter': 'default',
            'filename': LOGFILE,
        },
        'django.server': DEFAULT_LOGGING['handlers']['django.server'],
    },
    'loggers': {
        # default for all undefined Python modules
        '': {
            'level': PYTHON_LOGLEVEL,
            'handlers': ['console'],
        },
        # Our application code
        'chealth': {
            'level': LOGLEVEL,
            'handlers': ['console', 'file'],
            # Avoid double logging because of root logger
            'propagate': False,
        },
        # Default runserver request logging
        'django.server': DEFAULT_LOGGING['loggers']['django.server'],
    },
})

# Social Auth
SOCIAL_AUTH_INACTIVE_USER_LOGIN = True
SOCIAL_AUTH_INACTIVE_USER_URL = '/user/auth/iu/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/user/auth/error/'
SOCIAL_AUTH_JSONFIELD_ENABLE = True
SOCIAL_AUTH_FACEBOOK_KEY = config('SOCIAL_AUTH_FACEBOOK_KEY', default='')
SOCIAL_AUTH_FACEBOOK_SECRET = config('SOCIAL_AUTH_FACEBOOK_SECRET', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', default='')

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

# PostHog
PH_API_KEY = config('PH_API_KEY', default='')
PH_API_HOST = config('PH_API_HOST', default='')
PH_DISTINCT_ID_PREFIX = config('PH_DISTINCT_ID_PREFIX', default='')

# django-alexa for Alexa Custom Skills
ALEXA_APP_ID_DEFAULT = config('ALEXA_APP_ID_DEFAULT', default='')
ALEXA_REQUEST_VERIFICATION = config('ALEXA_REQUEST_VERIFICATION', default=True)

# firebase-admin
GOOGLE_APPLICATION_CREDENTIALS = config('GOOGLE_APPLICATION_CREDENTIALS', default='')

# s_nursing_faculty snowflake private key passphrase
S_NF_PASSPHRASE = config('S_NF_PASSPHRASE', default='')



